#!/bin/zsh
#
#エイリアスの設定

# 'cat hogehoge C'などでクリップボードにコピーできる
alias -g C='| pbcopy'


# ==========================================
# shell関係のエイリアス
# ==========================================
alias e='exit'
alias reload="source $HOME/.zshrc"

alias vi="nvim"
alias ls='exa'
alias l='ls'
alias la='ls -all'

# ==========================================
# git関係のエイリアス
# ==========================================
alias g='git'
alias gl='git log --oneline -10'
alias gs='git status'
alias ga='git add'
alias gch='git checkout'
alias gc='git commit'
alias gb='git branch'
alias gcp='git cherry-pick'
alias gsw='git branch | fzf --height 20% | xargs git checkout'

# ==========================================
# function
# ==========================================

alias push=push
alias pull=pull
alias mkcd=mkcd

function pull {
  remote=$1;
  pull_command="git pull ${remote:-origin} HEAD";

  echo $pull_command;
  eval $pull_command
}

function push {
  remote=$1;
  push_command="git push ${remote:-origin} HEAD";

  echo $push_command;
  eval $push_command;
}

#mkdirとcdを一括で行う
function mkcd() {
    mkdir $1;
    cd $1;
}

