#!/bin/zsh
#
#エイリアスの設定

# 'cat hogehoge C'などでクリップボードにコピーできる
alias -g C='| pbcopy'

# ==========================================
# shell関係のエイリアス
# ==========================================
alias e='exit'
alias :q='exit' # よく打ってしまうので追加してみる
alias reload="source $HOME/.zshrc"

alias vi="nvim"
alias ls='exa'
alias l='ls'
alias la='ls -all'

# ==========================================
# git関係のエイリアス
# ==========================================
alias g='git'
alias gl='git log --oneline -10'
alias gs='git status'
alias ga='git add'
alias gch='git checkout'
alias gc='git commit'
alias gb='git branch'
alias mp='git commit --allow-empty -m "make PR" && git push'

alias repo="gh repo view --web"
alias pr="gh pr view --web"
alias bd="git branch --merged|egrep -v '\*|develop|master'|xargs git branch -d"

# ==========================================
# functions
# ==========================================

function pull() {
  remote=$1;
  branch=$2;
  pull_command="git pull ${remote:-origin} ${branch:-HEAD}";

  echo $pull_command;
  eval $pull_command
}

function push {
  remote=$1;
  branch=$2;
  push_command="git push ${remote:-origin} ${branch-HEAD}";

  echo $push_command;
  eval $push_command;
}

# 時たま欲しくなるので追加
function clone() {
  if [ -z $1 ]; then
    echo "Usage: $0 owner/repository" 1>&2
    return
  fi

  git clone https://github.com/$1.git
}

function fzf-history() {
  BUFFER=$(history -n -r 1 | sort | uniq | fzf)
  CURSOR=$#BUFFER
}
zle     -N   fzf-history
bindkey '^R' fzf-history
