# ===========================================================
# core plugins
# これがないと悲しくなるやつ
# ===========================================================

[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'neoclide/coc.nvim'
build = 'call coc#util#install()'
branch = 'release'
hook_add         = 'call hook#coc#load()'

# ファイルツリーのやつ
[[plugins]]
repo = 'scrooloose/nerdtree'

# ファイラー
[[plugins]]
repo = '/usr/local/opt/fzf'

[[plugins]]
repo = 'junegunn/fzf.vim'

# =====================================================
# カラースキーム
# =====================================================
[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'joshdick/onedark.vim'

[[plugins]]
repo = 'chriskempson/base16-vim'

[[plugins]]
repo = 'wadackel/vim-dogrun'

# =====================================================
# neovimをすこしいい感じにするやつ
# TODO ここにプラグインを足すときは説明コメントをすること(忘れちゃうから)
# =====================================================

# 自動でカッコを付けてくれるやつ
[[plugins]]
repo = 'mattn/vim-lexiv'

# wakatimeを使ってコーディング時間を見る
[[plugins]]
repo = 'wakatime/vim-wakatime'

#vimの行横に+や-で差分を表示してくれる．
[[plugins]]
repo = 'airblade/vim-gitgutter'

#コメントON/OFFを手軽に実行 ON/OFFはCtrl+-を二回
[[plugins]]
repo = 'tomtom/tcomment_vim'

# インデントを可視化
[[plugins]]
repo = 'Yggdroot/indentLine'

# j, k移動高速化
[[plugins]]
repo = 'rhysd/accelerated-jk'

# 検索終了後にハイライトを消す
[[plugins]]
repo = 'romainl/vim-cool'
hook_add = '''let g:CoolTotalMatches = 1'''

# vim起動画面を変更する
[[plugins]]
repo = 'mhinz/vim-startify'
hook_add = '''
let g:startify_custom_header = [
                  \ '                       █▀▀▄ █▀▀ █▀▀█ ▀█░█▀ ░▀░ █▀▄▀█',
                  \ '                       █░░█ █▀▀ █░░█ ░█▄█░ ▀█▀ █░▀░█',
                  \ '                       ▀░░▀ ▀▀▀ ▀▀▀▀ ░░▀░░ ▀▀▀ ▀░░░▀',
                  \ '              config by nasa <https://github.com/k-nasa/dotfile>',
                  \ ]
'''

# 下のラインをカスタマイズするやつ
[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
	let g:lightline = {
		\ 'colorscheme': 'wombat',
		\ 'active': {
			\ 'left': [ ['mode', 'paste'], ['readonly', 'filepath', 'modified'] ]
				\ },
		\ 'component_function':{
			\ 'filepath': 'FilePath'
				\ }
		\ }

	function! FilePath()
		if winwidth(0) > 90
			return expand("%:s")
		else
			return expand("%:t")
		endif
	endfunction

	" # show statusbar
	set laststatus=2
	" # hide --INSERT--
	set noshowmode
'''

#行末の半角スペースを可視化FixWhitespaceで削除
[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

# =====================================================
# 言語ごとのプラグイン
# シンタックスハイライト、Linter等
# TODO on_ft = '言語' を書いて適用範囲を制限すること
# =====================================================

#clangのためのプラグイン
[[plugins]]
repo = 'vim-jp/cpp-vim'
on_ft = 'c'

# Dart
[[plugins]]
repo = 'dart-lang/dart-vim-plugin'
on_ft = 'dart'
hook_add  = '''
au BufNewFile,BufRead *.dart :set filetype=dart
'''

# Rust
[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft = 'rust'
hook_add = '''
    let g:rustfmt_autosave = 1
    let g:rustfmt_command = '$HOME/.cargo/bin/rustfmt'
'''

# ruby用 ---------
[[plugins]]
repo = 'fishbullet/deoplete-ruby'
on_ft = 'ruby'

# endを自動で入れてくれるやる
[[plugins]]
repo = 'tpope/vim-endwise'
on_ft = 'ruby'

[[plugins]]
repo = 'slim-template/vim-slim'
on_ft = 'ruby'

#css用
[[plugins]]
repo = "gko/vim-coloresque"
on_ft = 'css'

#js用
[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = 'javascript'

# CoffeeScript用
[[plugins]]
repo = 'kchmck/vim-coffee-script'
on_ft = 'javascript'

# いろいろフォーマッター
[[plugins]]
repo     = 'prettier/vim-prettier'
build    = 'npm install'
on_ft    = ['javascript', 'typescript', 'css', 'scss', 'json', 'markdown', 'yaml', 'html']
hook_source = '''
  " @formatアノテーションを持ったファイルの自動フォーマットを無効にする
  let g:prettier#autoformat = 0

  " Prettierのパースエラーをquickfixに表示しない
  let g:prettier#quickfix_enabled = 0

  autocmd BufWritePre *.js,*.ts,*.vue,*.css,*.scss,*.json,*.md PrettierAsync
'''

# vue.js用
[[plugins]]
repo = 'posva/vim-vue'
on_ft = 'vue'

#html
[[plugins]]
repo = 'rchaser53/insertclosetag'
on_ft = 'html'

[[plugins]]
repo =  'othree/html5.vim'
on_ft = 'html'

# Elm用
repo = 'ElmCast/elm-vim'
on_ft = 'elm'

# typescript -----------------
[[plugins]]
repo = "leafgarland/typescript-vim"
on_ft = 'typescript'

[[plugins]]
repo = "peitalin/vim-jsx-typescript"
on_ft = 'typescript'

# golang用 --------------------
[[plugins]]
repo = 'fatih/vim-go'
on_ft = 'go'
hook_add = '''
let g:go_fmt_command = "goimports"
'''
# let g:go_metalinter_autosave = 1
# let g:go_metalinter_autosave_enabled = ['vet']
