# ===========================================================
# core plugins
# これがないと悲しくなるやつ
# ===========================================================

[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'

# 非同期シンタックスチェック
[[plugins]]
repo = 'w0rp/ale'
hook_add = 'call hook#ale#load()'

# コードの自動補完
[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_i = 1
hook_add = 'let g:deoplete#enable_at_startup = 1'

# =====================================================
# lnagage server client
# =====================================================
[[plugins]]
repo             = 'autozimu/LanguageClient-neovim'
rev              = 'next'
# プラグインが読み込まれる際に呼び出されるコールバック
depends = 'deoplete.nvim'
on_ft = ['ruby']
build = './install.sh'
hook_add         = 'call hook#language_client_neovim#load()'


# なんであるのかあんまり覚えてないやつ -------------------
# vim8でdeopleteを使うのに必要
[[plugins]]
repo = 'roxma/nvim-yarp'
on_ft = ['ruby']

# vim8でdeopleteを使うのに必要
[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'
on_ft = ['ruby']


[[plugins]]
repo ='Shougo/neomru.vim'

[[plugins]]
repo = 'cohama/lexima.vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

# --------------------------------------------------------

#clangのためのプラグイン
[[plugins]]
repo = 'vim-jp/cpp-vim'

# Dart
[[plugins]]
repo = 'dart-lang/dart-vim-plugin'

#行末の半角スペースを可視化FixWhitespaceで削除
repo = 'bronson/vim-trailing-whitespace'

#ruby用
[[plugins]]
repo = 'fishbullet/deoplete-ruby'
# endを自動で入れてくれるやる
[[plugins]]
repo = 'tpope/vim-endwise'

#Rails用
[[plugins]]
repo = "tpope/vim-rails"
[[plugins]]
repo ="basyura/unite-rails"
[[plugins]]
repo = 'slim-template/vim-slim'

#haskell
[[plugins]]
repo = 'neovimhaskell/haskell-vim'
[[plugins]]
repo = 'ujihisa/neco-ghc'


#css用
[[plugins]]
repo = "gko/vim-coloresque"
[[plugins]]
repo = 'AtsushiM/sass-compile.vim'

#js用
[[plugins]]
repo = 'pangloss/vim-javascript'
[[plugins]]
repo = 'mxw/vim-jsx'

# vue.js用
[[plugins]]
repo = 'posva/vim-vue'
#html
[[plugins]]
repo = 'rchaser53/insertclosetag'
[[plugins]]
repo =  'othree/html5.vim'

#emmet-vim htmlが楽に書けるやつ
[[plugins]]
repo = 'mattn/emmet-vim'

#カラースキーム
[[plugins]]
repo = 'tomasr/molokai'

# ファイルツリーのやつ
[[plugins]]
repo = 'scrooloose/nerdtree'
# ファイラー
[[plugins]]
repo ='Shougo/unite.vim'


#vimの行横に+や-で差分を表示してくれる．
[[plugins]]
repo = 'airblade/vim-gitgutter'

#コメントON/OFFを手軽に実行 ON/OFFはCtrl+-を二回
[[plugins]]
repo = 'tomtom/tcomment_vim'

# インデントを可視化
[[plugins]]
repo = 'Yggdroot/indentLine'

# j, k移動高速化
[[plugins]]
repo = 'rhysd/accelerated-jk'

#vimないでgitを使うためのプラグイン
[[plugins]]
repo = 'tpope/vim-fugitive'

# 下のラインをカスタマイズするやつ
[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
	let g:lightline = {
		\ 'colorscheme': 'wombat',
		\ 'active': {
			\ 'left': [ ['mode', 'paste'], ['readonly', 'filepath', 'modified'] ]
				\ },
		\ 'component_function':{
			\ 'filepath': 'FilePath'
				\ }
		\ }

	function! FilePath()
		if winwidth(0) > 90
			return expand("%:s")
		else
			return expand("%:t")
		endif
	endfunction

	" # show statusbar
	set laststatus=2
	" # hide --INSERT--
	set noshowmode
'''
