# TODO extensionをインストールする実装
# TODO 要らなものを削除する

1yib.rust-bundle
aaron-bond.better-comments
antfu.slidev
apollographql.vscode-apollo
dbaeumer.vscode-eslint
denoland.vscode-deno
dustypomerleau.rust-syntax
eamodio.gitlens
esbenp.prettier-vscode
flowtype.flow-for-vscode
github.copilot
github.copilot-chat
github.copilot-labs
github.github-vscode-theme
golang.go
graphql.vscode-graphql
graphql.vscode-graphql-syntax
hashicorp.terraform
koichisasada.vscode-rdbg
ms-azuretools.vscode-docker
ms-ceintl.vscode-language-pack-ja
ms-python.debugpy
ms-python.python
ms-python.vscode-pylance
ms-toolsai.jupyter
ms-vscode-remote.remote-containers
ms-vscode-remote.remote-ssh
ms-vscode-remote.remote-ssh-edit
ms-vscode.makefile-tools
ms-vscode.remote-explorer
ms-vsliveshare.vsliveshare
orta.vscode-twoslash-queries
rust-lang.rust-analyzer
serayuzgur.crates
shardulm94.trailing-spaces
shopify.ruby-extensions-pack
shopify.ruby-lsp
sorbet.sorbet-vscode-extension
styled-components.vscode-styled-components
stylelint.vscode-stylelint
sysoev.vscode-open-in-github
tamasfe.even-better-toml
vscodevim.vim
wallabyjs.console-ninja
wayou.vscode-todo-highlight
wmaurer.change-case
yoavbls.pretty-ts-errors
yzane.markdown-pdf
zhuangtongfa.material-theme
