# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#
export PATH="$HOME/.rbenv/bin:$PATH"
export PATH=$HOME/.composer/vendor/bin:$PATH
export GOPATH=$HOME/.go
export PGDATA=/usr/local/var/postgres
# Source Prezto.
eval "$(rbenv init -)"
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi
export XDG_CONFIG_HOME=~/.config

#エイリアス用の関数定義
function mkcd() {
    mkdir $1;
    cd $1;
}

function push(){
  echo  "Please enter the commit message for your changes."
  read msg
  git add .
  git commit -m "$msg"
  git push
}

function deploy(){
  echo  "Please enter the commit message for your changes."
  read msg
  git add .
  git commit -m "$msg"
  git push heroku master
}


#エイリアスの設定
alias vim='nvim'
alias -s rb='ruby'
alias -s py='python'
alias vimc='vim ~/.config/nvim/init.vim'
alias vimp='vim ~/.config/nvim/dein.toml'
alias mkcd=mkcd #mkdirとcdを一括で行う
alias push=push
alias deploy=deploy
alias vi="nvim"

#git関係のエイリアス
alias g='git'
alias gl='git log --oneline -10'
alias gs='git status'
alias ga='git add'
alias gch='git checkout'
alias gc='git commit'
alias gb='git branch'
alias gcp='git cherry-pick'


 #Customize to your needs...

export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)"
