#!/bin/bash
#
# bootstrap

big_info() {
  printf "\e[34m
==============================
$1
==============================\n\e[m"
}

info () {
  printf "\r  [ \033[00;34mINFO\033[0m ] $1\n"
}

success () {
  printf "\r\033[2K  [  \033[00;32mOK\033[0m  ] $1\n"
}

error() {
  printf "[\033[00;31mERROR\033[0m] $1\n"
}

make_links() {
  mkdir -p $HOME/.config/
  # 各種ファイルのシンボリックリンクを貼る
  ln -sf $(pwd)/nvim $HOME/.config
  ln -sf $(pwd)/mise $HOME/.config

  DOTFILES="""
    shell/.zshrc
    shell/.zprofile
    shell/paths
    shell/aliases
    shell/zinit
    shell/env
    shell/prompt
    shell/lazy_load
    shell/secret_env
    git/.gitignore_global
    git/.gitconfig
    git/.commit_template
    .Brewfile
    """

    info "start create dotfile links"

    for dotfile in $DOTFILES
    do
      info "link $(pwd)/$dotfile to $HOME"
      ln -fns $(pwd)/$dotfile $HOME
    done

    success "Sucess create dotfile links"
  }

homebrew() {
  info "check installed homebrew"

  if hash brew 2>/dev/null; then
    info "homebrew already installed"
  else
    info 'brew not found. try install homebrew'

    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

    success "success install homebrew"
  fi

  info 'Install `brew` dependencies...'
  brew bundle --global -v -f

  success "success Install `brew` dependencies"
}

switch_to_zsh() {
  zsh
}

install_rustup() {
  info "check installed rustup"

  if hash rustup 2>/dev/null; then
    info "rustup already installed"
  else
    info "install rustup"
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh

    success "success Install rustup"
  fi

  success "finished rustup"
}

install_python() {
  info "install python"
  VERSION2=2.7.17
  VERSION3=3.8.2

  brew install pyenv

  pyenv install $VERSION2
  pyenv install $VERSION3
  pyenv global $VERSION3

  success "success Install node"
}

install_node() {
  info "install node"

  brew install nodenv

  VERSION=13.11.0
  nodenv install $VERSION
  nodenv global $VERSION

  success "success Install node"
}

install_ruby() {
  info "install node"

  brew install rbenv

  VERSION=2.7.2
  rbenv install $VERSION
  rbenv global $VERSION

  success "success Install node"

}

bootstrap_nvim() {
	npm install -g neovim

	pip3 install neovim
}

install_golang() {
  info "DOTO implement install_golang"
}


main() {
  big_info "start bootstrap!!"

  make_links
  homebrew

  big_info "install languages"
  install_rustup
  install_python
  install_node
  install_golang

  bootstrap_nvim

  success "Finished!!"
}

main
