#!/bin/bash
#
# bootstrap

info () {
  printf "\r  [ \033[00;34mINFO\033[0m ] $1\n"
}

success () {
  printf "\r\033[2K  [  \033[00;32mOK\033[0m  ] $1\n"
}


make_links() {
  # 各種ファイルのシンボリックリンクを貼る
  ln -sf .dotfile/nvim ~/.config/nvim

  DOTFILES="""
    shell/.zshrc
    shell/.zprofile
    shell/paths
    shell/aliases
    git/.gitignore_global
    git/.gitconfig
    git/.commit_template
    .Brewfile
    """

    info "start create dotfile links"

    for dotfile in $DOTFILES
    do
      info "link $(pwd)/$dotfile to $HOME"
      ln -fns $(pwd)/$dotfile $HOME
    done

    success "Sucess create dotfile links"
  }

homebrew() {
  info "check installed homebrew"

  brew --version > /dev/null
  if [ $? -ne 0 ]; then
    info 'brew not found. try install homebrew'

    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

    success "success install homebrew"
  else
    info "homebrew already installed"
  fi

  brew bundle check --global
  if [ $? -ne 0 ]; then
    info 'Install `brew` dependencies...'
    brew bundle --global -v

    success "success Install `brew` dependencies"
  else
    info '`brew` dependencies are satisfied'
  fi
}

install_rustup() {
  info "check installed rustup"

  rustup --version > /dev/null
  if [ $? -ne 0 ]; then
    info "install rustup"
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh

    success "success Install rustup"
  else
    info "rustup already installed"
  fi

  success "finished rustup"
}

setting_default_shell() {
  info "change default shell to zsh"

  chsh -s /usr/local/bin/zsh

  success "success change default shell"
}


main() {
  make_links
  homebrew
  setting_default_shell

  install_rustup

  success "Finished!!"
}

main
