#!/bin/bash

big_info() {
  printf "\e[34m
==============================
$1
==============================\n\e[m"
}

info () {
  printf "\r  [ \033[00;34mINFO\033[0m ] $1\n"
}

success () {
  printf "\r\033[2K  [  \033[00;32mOK\033[0m  ] $1\n"
}

error() {
  printf "[\033[00;31mERROR\033[0m] $1\n"
}

command_check() {
  if type $1 > /dev/null 2>&1; then
    success "$1"
  else
    error "$1"
  fi
}

check() {
  big_info "install checking!"

  COMMANDS=(brew rustup python node nvim zsh docker rbenv pyenv nodenv)

  for c in ${COMMANDS[@]}; do
    command_check $c
  done
}

main() {
  check
}

main
