name: Test Bootstrap

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  bootstrap:
    runs-on: [macos-latest]
    steps:
    - uses: actions/checkout@v2

    - name: Cleanup macOS
      run: |
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/uninstall.sh)"
        sudo rm -rf /Applications/Xcode.app \
        /Library/Developer/CommandLineTools
        sudo xcode-select --reset

    - name: Run bootstrap
      run: ./script/bootstrap
